# Basic Data to Train the AI to understand what's spam or not
data = [
    # Our Spam Examples
    ("Win a Free prize!", "spam"),
    ("Claim your lottery winnings now!", "spam"),
    ("Urgent: Your account is suspended!", "spam"),
    ("Get rich quick!!!", "spam"),
    ("VIAGRA - Lowest price!", "spam"),
    ("URGENT: Your Account Has Been Suspended!", "spam"),
    ("Claim Your FREE Lottery Winnings Now!", "spam"),
    ("Limited Time Offer - Get Rich Quick!", "spam"),
    ("Viagra Online - Best Prices!", "spam"),
    ("You've Won a Trip to The Bahamas!", "spam"),
    ("Verify Your Bank Account Information", "spam"),
    ("Investment Opportunity: High Returns Guaranteed", "spam"),
    ("Act Now: Your Package is Awaiting Delivery", "spam"),
    ("Exclusive Discount Just For You!", "spam"),
    ("Weight Loss Pills That Actually Work!", "spam"),
    ("Congratulations! You've Been Selected!", "spam"),
    ("Unsubscribe to Stop Receiving These Emails", "spam"),
    ("FW: Important Security Alert for Your Email", "spam"),
    ("Your Order #12345 Has Shipped (Check Details)", "spam"),
    ("Attention: Final Notice - Account Closure", "spam"),
    ("New Sex Enhancement Product!", "spam"),
    ("Your Credit Card Statement Is Ready", "spam"),
    ("Don't Miss Out on This Amazing Deal!", "spam"),
    ("Urgent Action Required: PayPal Account", "spam"),
    ("Huge Savings on Pharmaceuticals!", "spam"),
    ("A Message From Your Local Prince", "spam"),
    ("Free Gift Card - Click Here!", "spam"),
    ("Your Netflix Account is On Hold", "spam"),
    ("Bitcoin Investment - 1000% Profit!", "spam"),
    ("Lose 20 lbs in 2 Weeks!", "spam"),
    ("Important Tax Refund Notification", "spam"),
    ("Work From Home - Earn $5000 Daily!", "spam"),
    ("Your Amazon Prime Membership Expired", "spam"),
    ("Boost Your SEO Rankings Instantly!", "spam"),
    ("Re: Undelivered Mail Returned to Sender", "spam"),
    ("Cialis Generics Available Now", "spam"),
    ("Get Your Degree Online - Fast!", "spam"),
    ("Official Prize Notification!", "spam"),
    ("Your Order Could Not Be Processed", "spam"),
    ("Winning Confirmation - ID 7890", "spam"),
    ("Debt Relief - Erase Your Debts!", "spam"),
    ("New Followers on Your Social Media!", "spam"),
    ("Your Apple ID Has Been Locked", "spam"),
    ("Guaranteed Loan Approval - No Credit Check", "spam"),
    ("Special Offer: Extend Your Warranty", "spam"),
    ("Confidential Business Proposal", "spam"),
    ("Click to Claim Your $1,000,000 Prize", "spam"),
    ("Notification: Pending Shipment", "spam"),
    ("Improve Your Love Life Tonight!", "spam"),
    ("Important Message From The IRS", "spam"),
    ("Last Chance to Qualify!", "spam"),
    ("Make Money Online - Simple Steps", "spam"),
    ("Your Security Code is 45678", "spam"),
    ("Discounted Software Keys!", "spam"),
    ("Your Account Needs Immediate Attention", "spam"),
    ("We Miss You! Here's a Special Offer", "spam"),
    ("Enhance Your Performance!", "spam"),
    ("Urgent Payment Required", "spam"),
    ("Discover How to Retire Early", "spam"),
    ("New Customer Bonus - Don't Wait!", "spam"),
    ("Re: Fwd: Important Document", "spam"),
    ("Your Data Has Been Compromised", "spam"),
    ("Huge Black Friday Deals Are Here!", "spam"),
    ("Get Instant Cash Advance!", "spam"),
    ("Official Notification of Inheritance", "spam"),
    ("Lower Your Mortgage Payments!", "spam"),
    ("Exclusive Invitation - Private Event", "spam"),
    ("Your Domain Name Is Expiring!", "spam"),
    ("Buy Gold and Silver Online", "spam"),
    ("New Friends Request on Facebook", "spam"),
    ("Free Sample of Our Amazing Product", "spam"),
    ("Protect Your Identity - Enroll Now!", "spam"),
    ("You Have a New Message!", "spam"),
    ("Earn Passive Income with Crypto", "spam"),
    ("Your Subscription Has Auto-Renewed", "spam"),
    ("Secret to Younger Looking Skin", "spam"),
    ("Action Required: Your Funds are Frozen", "spam"),
    ("Limited Stock - Order Today!", "spam"),
    ("Regarding Your Outstanding Invoice", "spam"),
    ("Get Free Traffic to Your Website!", "spam"),
    ("Your Phone Has Been Hacked!", "spam"),
    ("Financial Aid Opportunity Inside", "spam"),
    ("Your Device Is Under Attack!", "spam"),
    ("New Dating Profiles Near You!", "spam"),
    ("Claim Your Cash Today!", "spam"),
    ("Regarding Your Recent Purchase", "spam"),
    ("High-Interest Savings Account!", "spam"),
    ("Final Warning: Your Account Will Be Deleted", "spam"),
    ("Unlock Your Potential Now!", "spam"),
    ("Your Personal Information Needed", "spam"),
    ("Special Offer for Senior Citizens", "spam"),
    ("Verify Your Recent Activity", "spam"),
    ("Learn a New Language in 7 Days!", "spam"),
    ("Your Computer Has a Virus!", "spam"),
    ("Don't Reply - Read This Now!", "spam"),
    ("Exclusive Webinar Invitation", "spam"),
    ("Urgent Update Required for Your Browser", "spam"),
    ("You've Qualified for a Refund", "spam"),
    ("New Message from a Secret Admirer", "spam"),
    ("Protect Your Home from Intruders", "spam"),
    ("Your Credit Score Just Improved!", "spam"),
    ("Congratulations! You're a Winner!", "spam"),
    ("Get a Free Trial Today!", "spam"),
    ("Important Notification from Shipping Carrier", "spam"),
    ("Your IP Address Has Been Compromised", "spam"),
    ("Meet Singles in Your Area!", "spam"),
    ("Clear Your Criminal Record Fast!", "spam"),
    ("Your Online Security Is At Risk", "spam"),
    ("Discount on All Leading Brands", "spam"),
    ("New Government Grants Available", "spam"),
    ("Your Account Is Overdue", "spam"),
    ("Get Paid to Take Surveys!", "spam"),
    ("Your Private Photos Exposed!", "spam"),
    ("Big Savings Inside - Click Here!", "spam"),
    ("Official Lottery Results Notification", "spam"),
    ("We Have Your Password", "spam"),
    ("Your Personal Invitation to Success", "spam"),
    ("Regarding Your Recent Order", "spam"),
    ("Increase Your Muscle Mass Quickly!", "spam"),
    ("Your Device Needs an Update", "spam"),
    ("Don't Miss This Investment!", "spam"),
    ("New Job Opportunities for You", "spam"),
    ("Your Email Has Been Flagged", "spam"),
    ("Exclusive Access for VIP Members", "spam"),
    ("Fix Your Relationship Problems Now", "spam"),
    ("Urgent: Tax Documents Pending", "spam"),
    ("Free Samples for New Customers", "spam"),
    ("Your Account Has Unauthorized Activity", "spam"),
    ("Amazing New Product Launch!", "spam"),
    ("You Are Our Lucky Winner!", "spam"),
    ("Cash Flow Solutions for Your Business", "spam"),
    ("Your Loan Application Approved", "spam"),
    ("Warning: Suspicious Login Attempt", "spam"),
    ("New Way to Make Money Online", "spam"),
    ("Your Package is Held at Customs", "spam"),
    ("Exclusive Real Estate Investment", "spam"),
    ("Get Your Dream Body Today!", "spam"),
    ("Verify Your Contact Information", "spam"),
    ("Important Security Update for Your PC", "spam"),
    ("Meet Local Singles Tonight!", "spam"),
    ("Your Prize is Waiting!", "spam"),
    ("Regarding Your Social Security Number", "spam"),
    ("Limited Offer: Free Consultation", "spam"),
    ("Your Bank Account Alert", "spam"),
    ("How to Get Six Pack Abs Fast", "spam"),
    ("New Message from Your Bank", "spam"),
    ("You've Been Invited to a Secret Group", "spam"),
    ("Protect Your Family From Harm", "spam"),
    ("Your Online Profile Needs Verification", "spam"),
    ("Unlock Your Inner Potential", "spam"),
    ("Urgent: Your Invoice is Due", "spam"),
    ("Win a Brand New Car!", "spam"),
    ("Your Account Will Be Deleted Soon", "spam"),
    ("New Treatment for Erectile Dysfunction", "spam"),
    ("Your Data Privacy Alert", "spam"),
    ("Get Instant Debt Consolidation", "spam"),
    ("Important Notice: Account Verification", "spam"),
    ("New Way to Make $10,000 Monthly", "spam"),
    ("Your Password Expired - Reset Now", "spam"),
    ("Exclusive Crypto Mining Opportunity", "spam"),
    ("You Have a Delivery Scheduled", "spam"),
    ("Regarding Your Unclaimed Funds", "spam"),
    ("Boost Your Energy Levels Naturally", "spam"),
    ("Your Computer Has Critical Errors", "spam"),
    ("New Opportunities for Financial Freedom", "spam"),
    ("Your Profile Has Been Viewed!", "spam"),
    ("Urgent: Final Reminder for Payment", "spam"),
    ("Free Vacation Package for You!", "spam"),
    ("Your Account Has Been Compromised", "spam"),
    ("Amazing Deals on Prescription Drugs", "spam"),
    ("Get Instant Access to Our Exclusive Club", "spam"),
    ("Your Tax Return Is Missing Information", "spam"),
    ("New System Update Required", "spam"),
    ("Important Alert from Customer Support", "spam"),
    ("You've Been Pre-Approved!", "spam"),
    ("Regarding Your Security Breach", "spam"),
    ("Improve Your Memory Overnight!", "spam"),
    ("Your Email Account Is Full", "spam"),
    ("New Investment Strategy Revealed", "spam"),
    ("Your Personal Data Is Vulnerable", "spam"),
    ("Act Fast: Limited Spots Available", "spam"),
    ("Your Refund is Pending", "spam"),
    ("Get a Second Passport Now!", "spam"),
    ("Urgent: Delivery Problem!", "spam"),
    ("New Bitcoin Giveaway!", "spam"),
    ("Your Credit Card Activity Alert", "spam"),
    ("Learn How to Trade Stocks Easily", "spam"),
    ("Your Phone Number Has Been Leaked", "spam"),
    ("Exclusive Offer for Loyal Customers", "spam"),
    ("Your Online Banking Alert", "spam"),
    ("Get Rid of Belly Fat Quickly!", "spam"),
    ("Important Message from Your Provider", "spam"),
    ("You Have a New Friend Request", "spam"),
    ("Secure Your Future with Gold", "spam"),
    ("Your Account is Locked Temporarily", "spam"),
    ("New Health Discovery!", "spam"),
    ("Urgent: Respond Immediately", "spam"),
    ("Free Ebook: How to Get Rich", "spam"),
    ("Your Account Security Alert", "spam"),
    ("Meet Russian Singles Online!", "spam"),
    ("Congratulations! You're Approved!", "spam"),
    ("Special Offer: 50% Off Everything!", "spam"),
    ("Your Identity Is At Risk", "spam"),
    ("New Work From Home Opportunity", "spam"),
    ("Your Package is Delayed", "spam"),
    ("Important: Your Personal Data", "spam"),
    ("Boost Your Brain Power Now!", "spam"),
    ("Your Email Has Been Compromised", "spam"),
    ("Urgent: Your Bitcoin Wallet", "spam"),
    ("New Government Stimulus Check", "spam"),
    ("Your Loan Application Status", "spam"),
    ("Secret to a Longer Life!", "spam"),
    ("Your Amazon Account Has Been Hacked", "spam"),
    ("Free Stock Trading Account!", "spam"),
    ("You Have a New Voicemail", "spam"),
    ("Official Notification: Legal Action", "spam"),
    ("Lose Weight Without Exercise!", "spam"),
    ("Your Account has Unusual Activity", "spam"),
    ("New Exclusive Membership Offer", "spam"),
    ("Urgent: Last Chance to Update Info", "spam"),
    ("Free Money for Your Business!", "spam"),
    ("Your Computer Security Warning", "spam"),
    ("Get Your Dream Job Today!", "spam"),
    ("Your Online Payment Failed", "spam"),
    ("Important: Your Personal Records", "spam"),
    ("Unlock Hidden Wealth!", "spam"),
    ("Your Credit Card Was Declined", "spam"),

    #Our Not Spam Examples
    ("Hello, how are you?", "not spam"),
    ("Meeting reminder for tomorrow.", "not spam"),
    ("Please review the document.", "not spam"),
    ("Can we reschedule the call?", "not spam"),
    ("Project update meeting", "not spam"),
    ("Meeting Reminder: Project Alpha Standup", "not spam"),
    ("Regarding our discussion yesterday", "not spam"),
    ("Updated Team Schedule for Q3", "not spam"),
    ("Invoice for July Services - [Company Name]", "not spam"),
    ("Your Flight Confirmation - [Airline/Flight No.]", "not spam"),
    ("Request for Documents: HR Onboarding", "not spam"),
    ("Follow-up: Interview with [Candidate Name]", "not spam"),
    ("Question about your recent order #12345", "not spam"),
    ("Weekly Project Sync - Agenda Attached", "not spam"),
    ("Action Required: Review of Annual Report", "not spam"),
    ("Your Subscription Renewal Notice", "not spam"),
    ("Password Reset Confirmation for [Service]", "not spam"),
    ("Invitation: Company Holiday Party", "not spam"),
    ("Feedback on your recent purchase", "not spam"),
    ("New PTO Request from [Employee Name]", "not spam"),
    ("Your Monthly Utility Bill is Ready", "not spam"),
    ("Re: Question about contract terms", "not spam"),
    ("Thank you for your application to [Job Title]", "not spam"),
    ("Software Update Available - [Product Name]", "not spam"),
    ("Your Appointment Reminder - [Date/Time]", "not spam"),
    ("Important: System Maintenance Tonight", "not spam"),
    ("Welcome to [Service Name]!", "not spam"),
    ("Delivery Update: Your Package from [Store Name]", "not spam"),
    ("Team Lunch Plan for Friday", "not spam"),
    ("Reminder: Performance Review Deadlines", "not spam"),
    ("Your Account Activity Statement", "not spam"),
    ("Quick question about the presentation", "not spam"),
    ("Confirmation: Your Registration for [Event]", "not spam"),
    ("New Policy Update: Remote Work Guidelines", "not spam"),
    ("Your Pay Stub is Available", "not spam"),
    ("FYI: Office Closure on [Date]", "not spam"),
    ("Check-in: How's [Project Name] coming along?", "not spam"),
    ("Important Message from Your Bank", "not spam"),
    ("Meeting Notes from [Meeting Name] - [Date]", "not spam"),
    ("Your Order Has Been Shipped - Tracking Info", "not spam"),
    ("Request for Quote - [Service/Product]", "not spam"),
    ("Regarding your inquiry about [Topic]", "not spam"),
    ("New Ticket Assigned: [Ticket ID] - [Issue Summary]", "not spam"),
    ("Your Schedule for Next Week", "not spam"),
    ("Upcoming Webinar: [Topic] - Register Now", "not spam"),
    ("Update on Q2 Financials", "not spam"),
    ("Access Granted: [System/Resource]", "not spam"),
    ("Your IT Support Request Has Been Closed", "not spam"),
    ("Reminder: Expense Report Submission", "not spam"),
    ("Action Item: Review Document [Link/Name]", "not spam"),
    ("Welcome Aboard! - [New Employee Name]", "not spam"),
    ("Changes to Your Service Agreement", "not spam"),
    ("Your Daily Digest from [App Name]", "not spam"),
    ("Notice of Planned Outage - [Service Name]", "not spam"),
    ("Proposal for [Project/Client]", "not spam"),
    ("Important Information About Your Benefits", "not spam"),
    ("Re: Follow up on task [Task Name]", "not spam"),
    ("Congratulations on Your Promotion!", "not spam"),
    ("Your Payment Confirmation", "not spam"),
    ("New Document Shared With You", "not spam"),
    ("Feedback on your recent support ticket", "not spam"),
    ("Reminder: Upcoming Holiday", "not spam"),
    ("Your Statement from [Financial Institution]", "not spam"),
    ("Agenda for [Meeting Name]", "not spam"),
    ("Your Delivery Confirmation", "not spam"),
    ("Question about the project roadmap", "not spam"),
    ("Annual Leave Request from [Employee Name]", "not spam"),
    ("Update: Your Account Details", "not spam"),
    ("Invitation to Connect on LinkedIn", "not spam"),
    ("Project [X] Status Update", "not spam"),
    ("Regarding your recent application", "not spam"),
    ("Action Required: Complete Training Module", "not spam"),
    ("Your Recent Login Activity", "not spam"),
    ("New message from [Colleague Name]", "not spam"),
    ("Your Weekly Newsletter from [Source]", "not spam"),
    ("FYI: New Company Policy", "not spam"),
    ("Request for feedback on [Document/Project]", "not spam"),
    ("Your Order # [Number] Update", "not spam"),
    ("Important System Alert: [Alert Type]", "not spam"),
    ("Your [Product/Service] License Expiring Soon", "not spam"),
    ("Re: [Previous Email Subject]", "not spam"),
    ("Meeting Cancellation/Reschedule", "not spam"),
    ("Your Support Case [Number] Update", "not spam"),
    ("New Article: [Topic]", "not spam"),
    ("Payment Confirmation for [Service]", "not spam"),
    ("Action: Please Approve [Item]", "not spam"),
    ("Your [Account Type] Statement is Ready", "not spam"),
    ("Regarding the pending task", "not spam"),
    ("New Comment on [Document Name]", "not spam"),
    ("Your Shipping Notification", "not spam"),
    ("Upcoming Event: [Event Name]", "not spam"),
    ("Internal Memo: [Topic]", "not spam"),
    ("Your Password Was Changed", "not spam"),
    ("Meeting with [Client Name] - Recap", "not spam"),
    ("Travel Itinerary for [Trip Name]", "not spam"),
    ("Reminder: Due Date for [Task]", "not spam"),
    ("Your Recent Purchases", "not spam"),
    ("New Message from Your [Team/Department]", "not spam"),
    ("Your Account Details Have Been Updated", "not spam"),
    ("Invitation: Join Our Webinar", "not spam"),
    ("Software Release Notes - Version [Number]", "not spam"),
    ("Your [Service] Bill for [Month]", "not spam"),
    ("Regarding your vacation request", "not spam"),
    ("Confirmation of Your Booking", "not spam"),
    ("FYI: Office Potluck Sign-up", "not spam"),
    ("Call with [Name] - Tomorrow at [Time]", "not spam"),
    ("Important Security Notice from [Company]", "not spam"),
    ("Your Newsletter Subscription Confirmation", "not spam"),
    ("New Feedback on your code review", "not spam"),
    ("Request for Timesheet Approval", "not spam"),
    ("Your New Employee Benefits Package", "not spam"),
    ("Update on [Feature Name] Development", "not spam"),
    ("Invoice # [Number] from [Company Name]", "not spam"),
    ("Meeting Room Booking Confirmation", "not spam"),
    ("Your Report for [Period] is Ready", "not spam"),
    ("Action Required: Renew Your Certificate", "not spam"),
    ("Welcome to the [Team Name] Team!", "not spam"),
    ("Your Daily Briefing", "not spam"),
    ("Notice of Annual General Meeting", "not spam"),
    ("Regarding the bug report [ID]", "not spam"),
    ("Your New Support Ticket Has Been Created", "not spam"),
    ("Check out our new blog post!", "not spam"),
    ("Security Alert: Suspicious Activity Detected", "not spam"),
    ("Your Password has been successfully reset", "not spam"),
    ("New training material available", "not spam"),
    ("Confirmation: Your Payment Received", "not spam"),
    ("Request for additional information", "not spam"),
    ("Your scheduled report is attached", "not spam"),
    ("Project status update for [Week/Month]", "not spam"),
    ("Invitation: Q4 Planning Session", "not spam"),
    ("Your account statement is now available", "not spam"),
    ("Update on [Customer Name] Account", "not spam"),
    ("Meeting Agenda: Next Steps", "not spam"),
    ("Your [Product] has shipped!", "not spam"),
    ("Regarding your request for a demo", "not spam"),
    ("Feedback on our recent survey", "not spam"),
    ("Your annual performance review is due", "not spam"),
    ("New software license agreement", "not spam"),
    ("Reminder: Upcoming Holiday Break", "not spam"),
    ("Your [Service] billing statement", "not spam"),
    ("FYI: New software updates", "not spam"),
    ("Important: Action Required for your account", "not spam"),
    ("Your recent login activity on [Service]", "not spam"),
    ("New document for review: [Doc Title]", "not spam"),
    ("Your daily digest: News and Updates", "not spam"),
    ("Meeting with [Colleague Name] - 1:1", "not spam"),
    ("Confirmation of your appointment", "not spam"),
    ("New expense report submitted by [Name]", "not spam"),
    ("Your flight check-in is now open", "not spam"),
    ("Regarding your question about [Topic]", "not spam"),
    ("Update on the customer feedback survey", "not spam"),
    ("Your new [Software Name] account details", "not spam"),
    ("Payment reminder for invoice [Number]", "not spam"),
    ("Team building event details", "not spam"),
    ("Your recent activity report", "not spam"),
    ("New feature alert: [Feature Name]", "not spam"),
    ("Regarding your data usage", "not spam"),
    ("Important safety notice: [Product/Service]", "not spam"),
    ("Your annual summary from [Service]", "not spam"),
    ("Meeting notes for [Date] - [Project]", "not spam"),
    ("Your password expiry notification", "not spam"),
    ("Confirmation of your order # [Number]", "not spam"),
    ("New content available on [Platform]", "not spam"),
    ("Regarding your recent support request", "not spam"),
    ("Action required: Verify your email address", "not spam"),
    ("Your monthly report from [Service]", "not spam"),
    ("Invitation to join [Team/Group]", "not spam"),
    ("Update on your submitted bug report", "not spam"),
    ("Your upcoming webinar registration", "not spam"),
    ("New security updates for your device", "not spam"),
    ("Regarding the project meeting minutes", "not spam"),
    ("Your certificate is expiring soon", "not spam"),
    ("Important update: New terms of service", "not spam"),
    ("Your recent activity on [Account]", "not spam"),
    ("New blog post from [Author/Website]", "not spam"),
    ("Your vacation request has been approved", "not spam"),
    ("Regarding the budget proposal", "not spam"),
    ("Your weekly summary from [Tool]", "not spam"),
    ("Invitation to a brainstorming session", "not spam"),
    ("Update on your subscription status", "not spam"),
    ("Your delivery is scheduled for [Date]", "not spam"),
    ("Regarding the Q3 objectives", "not spam"),
    ("Your network access has been updated", "not spam"),
    ("Important information regarding your privacy", "not spam"),
    ("Your monthly digest of [Topic]", "not spam"),
    ("New job openings at [Company Name]", "not spam"),
    ("Regarding the software deployment", "not spam"),
    ("Your account balance statement", "not spam"),
    ("Action required: Complete your profile", "not spam"),
    ("Your upcoming payment reminder", "not spam"),
    ("New document: [Meeting Name] Summary", "not spam"),
    ("Regarding the client feedback", "not spam"),
    ("Your data usage alert", "not spam"),
    ("Important: Action required for your [Service]", "not spam"),
    ("Your password change confirmation", "not spam"),
    ("New feature update for [App Name]", "not spam"),
    ("Regarding your IT request", "not spam"),
    ("Your account review is complete", "not spam")
]